export const todos = [
  {
    id: "LER",
    title: "make chips for secondary todos",
    description: "dlsfjdklsjfd f sdf s",
    tags: ["anime", "shounen", "action"],
    completed: false,
    createdAt: new Date(),
  },
  {
    id: "LER4",
    title: "Create Add Todo Modal",
    description: "dlsfjdklsjfd f sdf s",
    tags: ["crime", "drama"],
    completed: false,
    createdAt: new Date(),
  },
  {
    id: "LER3",
    title: "Go for a rundlskkjfdls jflkdsj flkds j",
    description: "dlsfjdklsjfd f sdf s",
    completed: true,
    createdAt: new Date(),
  },
  {
    id: "LER2",
    title: "Attend meeting at 2 PM",
    description: "dlsfjdklsjfd f sdf s",
    tags: ["romance", "comedy", "adventure"],
    completed: true,
    createdAt: new Date(),
  },
  {
    id: "LERWW",
    title: "firebase 🔥",
    description: "dlsfjdklsjfd f sdf s",
    tags: ["anime"],
    completed: false,
    createdAt: new Date(),
  },
  {
    id: "LEREWR",
    title: "Call a friend",
    description: "dlsfjdklsjfd f sdf s",
    tags: ["romance", "comedy"],
    completed: true,
    createdAt: new Date(),
  },
  {
    id: "LERCEWRC",
    title: "Integrate Backend",
    description: "dlsfjdklsjfd f sdf s",
    tags: ["crime", "drama", "thrill"],
    completed: false,
    createdAt: new Date(),
  },
];
